CREATE DEFINER=`root`@`localhost` PROCEDURE `column_permissions`(table_ VARCHAR(255))
BEGIN
SELECT COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = table_
    AND TABLE_SCHEMA = 'sop';
END