/*
-- Query: SELECT id AS UUID,
`name`,
brand_id,
product_subcategory_id AS category_id,
barcode_prefix AS product_id_prefix
FROM lagerdb.product_models
-- Date: 2023-06-22 09:00
*/
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (1,'Logitech H600 wireless headsets                         ',17,25,'HEADSET.H600.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (2,'GEARLAB G63 Webcam            ',17,31,'WEBCAM.G63.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (3,'OPTPLX780',1,98,'PC.OPTPLX780.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (4,'OPTPLX380',1,98,'PC.OPTPLX380.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (5,'LenovoM90',11,98,'PC.LenovoM90.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (6,'LenovoEdge71',11,98,'PC.LenovoEdge71.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (7,'LenovoA70',11,98,'PC.LenovoA70.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (8,'LenovoA58',11,98,'PC.LenovoA58.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (9,'HP Color LaserJet 2600n',17,64,'PRINTER.HP2600n.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (10,'HP LaserJet 2605dn',17,64,'PRINTER.HP2605dn.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (11,'Epson WF 2010 printer',17,64,'PRINTER.EpsonWF2010.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (12,'Epson XP 215 Printer',17,64,'PRINTER.EpsonXP215.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (13,'HP 6100 OfficeJet printer',17,64,'PRINTER.HP6100.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (14,'Cisco 2950 12-ports switch',17,51,'SWITCH.CISCO2950P12.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (15,'Atom',13,98,'PC.Atom.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (16,'Cisco 2921 Router',17,50,'ROUTER.CISCO2921.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (17,'Cisco 881 Router',17,50,'ROUTER.CISCO881.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (18,'Cisco 806 Router',17,50,'ROUTER.CISCO806.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (19,'Cisco 831 Router',17,50,'ROUTER.CISCO831.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (20,'Cisco 2801 Router',17,50,'ROUTER.CISCO2801.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (21,'Cisco 2821 Router',17,50,'ROUTER.CISCO2821.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (22,'Fujitsu Zero-Client skærm til f.eks hypervisor            ',12,97,'SKAERM.FzeroClient.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (23,'BAMBOO Tegneplade            ',17,86,'TEGNEPLADE.BAMBOO.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (24,'LG E2251VR-BN skærm',5,97,'SKAERM.LGE2251VR-BN.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (25,'AOC e234F skærm',3,97,'SKAERM.AOCe2343F.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (26,'LG FLATRON W2240',5,97,'SKAERM.LGFLTRW2240.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (27,'Dell p2210f skærm',1,97,'SKAERM.DELLP2210f.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (28,'HP LA2205WG skærm',2,97,'SKAERM.HPLA2205WG.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (29,'IBM 249824E 24 ports switch',17,51,'SWITCH.IBM249824EP24.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (30,'HP 210E 16 ports fiber channel switch',17,51,'FCSWITCH.HP2010EP16.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (31,'Cisco SFE2000P 24 ports POE Switch',17,51,'SWITCH.CISCOSFE2P24POE.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (32,'Dell PowerConnect 6248 48 ports switch',17,51,'SWITCH.DELLPC6248P48.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (33,'HP v1910 4 ports gigabit switch',17,51,'SWITCH.HPV1910P48G.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (34,'Cisco 2600XM router',17,50,'ROUTER.CISCO2600XM.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (35,'Cisco 5203 Router',17,50,'ROUTER.CISCO2503.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (36,'Router Cisco2600 ',17,50,'ROUTER.CISCO2600.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (37,'Havit USB headphone',17,25,'HEADSET.HAVIT.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (38,'FH5400 USB HEADSET TIL ELEV UDLÅN',17,25,'HEADSET.FH5400.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (39,'KONFERENCE TELEFON',17,25,'KONFTEL.510UC.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (40,'Zbiegniew mus',17,28,'MUS.MXMASTER3.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (41,'zBIEGNIEW DOCK            ',1,99,'DOCK.DELLZZM.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (42,'Cisco 2811 router',17,50,'ROUTER.CISCO2811.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (43,'HPELITEDESK800G3VR',2,98,'PC.HPELITEDESK800G3VR.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (44,'Cisco ASA 5540 Firewall',17,54,'FIREWALL.CISCO5540.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (45,'HP 2824 24 ports switch',17,51,'SWITCH.HP2824P24.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (46,'D-Link 1016D 16 ports Switch',17,51,'SWITCH.D-Link1016D.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (47,'CHIEFTECFEJLPC',10,98,'PC.CHIEFTECFEJLPC.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (48,'Linksys SFE1000P 8-ports gigabit switch med WebView og PoE',17,51,'SWITCH.LINKSYSSFE1000P.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (49,'HP ProCurve 1700-24 24 ports switch',17,51,'SWITCH.HP1700-24P24.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (50,'HP E273q 27\" Skærm',2,97,'SKAERM.HPE273Q.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (51,'Cisco 2960 48-ports switch            ',17,51,'SWITCH.CISCO2960P48.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (52,'Cisco 2960S 48-ports switch            ',17,51,'SWITCH.CISCO2960SP48.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (53,'Cisco 3550 24-ports switch',17,51,'SWITCH.CISCO3550P24.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (54,'Cisco 3550 48-ports switch',17,51,'SWITCH.CISCO3550P48.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (55,'Cisco 3500XL 24 ports switch            ',17,51,'SWITCH.CISCO3500XLP24.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (56,'Cisco 3500XL 48 ports switch',17,51,'SWITCH.CISCO3500XLP48.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (57,'Cisco 3560v2 48 ports switch',17,51,'SWITCH.CISCO3560V2P48.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (58,'Cisco 3560 48 ports switch',17,51,'SWITCH.CISCO3560P48.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (59,'Cisco 2950 48-ports switch',17,51,'SWITCH.CISCO2950P48.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (60,'Cisco 3750-E 24-ports switch',17,51,'SWITCH.CISCO3750EP24.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (61,'Cisco 3750-Metro 24-ports switch',17,51,'SWITCH.CISCO3750METP24.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (62,'Linksys SRW224G4 24-porte og 4 gigabit porte medWebView',17,51,'SWITCH.LINKSYSSRW224G4.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (63,'Linksys SR224 24-ports switch',17,51,'SWITCH.LINKSYSSR224.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (64,'Linksys SFE2010P 48-ports switch med PoE            ',17,51,'SWITCH.LINKSYSSFE2010P.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (65,'Linksys SFE2000P 24-ports switch med PoE',17,51,'SWITCH.LINKSYSSFE2000P.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (66,'Linksys SRW224P 24-port switch med WebView og PoE',17,51,'SWITCH.LINKSYSSRW224P.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (67,'Cisco 2960 8-ports switch',17,51,'SWITCH.CISCO2960P8.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (68,'Cisco 2900 Router',17,50,'ROUTER.CISCO2900.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (69,'Cisco 2800 Router',17,50,'ROUTER.CISCO2800.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (70,'Cisco 2502 Router',17,50,'ROUTER.CISCO2502.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (71,'Cisco PIX 506E FIREWALL',17,54,'FIREWALL.CISCOPIX506E.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (72,'Dell E2214HB Skærm',1,97,'SKAERM.DELLP2214HB.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (73,'Dell E2414H Skærm',1,97,'SKAERM.DELLE2414H.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (74,'DELLU2413',1,97,'SKAERM.DELLU2413.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (75,'Dell U2410F \"Radiator\" skærm',1,97,'SKAERM.DELLU2410F.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (76,'Buffalo LinkStation Pro Duo med 2x 500GB HDD ',17,56,'NAS.BUFFALOLSPRODUO.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (77,'Buffalo LinkStation Pro NAS 1x 250GB HDD',17,56,'NAS.BUFFALOLSPRO.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (78,'Synology DS110j  DiskStation NAS 1x 250GB HDD',17,56,'NAS.SYNOLOGYDS110J.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (79,'Synology DS212j  DiskStation NAS 2x 1TB HDD',17,56,'NAS.SYNOLOGYDS212j.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (80,'LinkSys Wireless-B Router Ethernet Brigde',17,50,'ROUTER.LINKSYSBRIGDGE.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (81,'LinkSys Wireless-N Broadband Networking Kit',17,50,'ROUTER.LINKSYSNWKIT.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (82,'Synology DS216j DiskStation NAS 2x 1TB HDD',17,56,'NAS.SYNOLOGYDS216J.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (83,'Synology DS112j DiskStation NAS 1x 500GB HDD (Mangler reset knap)',17,56,'NAS.SYNOLOGYDS112J.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (84,'Uibquity UniFi 802.11n Access Point 2.4 GHz 300 Mbps',17,53,'AP.UBIQUITY80211N.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (85,'Synology DS213j DiskStation NAS 1x 1TB HDD (Mangler reset knap) (Den øverste harddisk slot (HDD1) virker ikke, derfor er der kun 1 disk i NAS\"en)',17,56,'NAS.SYNOLOGYDS213J.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (86,'Synology DS211+ DiskStation NAS 2x 1TB HDD',17,56,'NAS.SYNOLOGYDS211PLS.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (87,'ZyXEL NSA 325 v2 Media Server NAS 2x 500GB HDD',17,56,'NAS.ZYXELNSA325V2.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (88,'QNAP TS-412 NAS 4x 1TB HDD',17,56,'NAS.QNAPTS412.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (89,'Acer V223HQ skærm',7,97,'SKAERM.ACERV223HQ.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (90,'DELL 1908FPB Skærm',1,97,'SKAERM.DELL1908FPB.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (91,'Cisco 2960PLUS 24-ports switch',17,51,'SWITCH.CISCO2960PLSP24.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (92,'BenQ DL2215B Skærm',6,97,'SKAERM.BENQ2215B.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (93,'Linksys E1200 Wireless home Router.',17,50,'ROUTER.LINKSYSE1200.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (94,'Linksys E2000 Advanced Wireless-N Router.',17,50,'ROUTER.LINKSYSE2000.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (95,'Linksys Wireless-N Broadband Router WRT160N V3',17,50,'ROUTER.LINKSYSWRT160N.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (96,'Linksys Wireless-G Broadband Router WRT54G2 V1',17,50,'ROUTER.LINKSYSWRT54G2.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (97,'D-Link Home Router DIR-100            ',17,50,'ROUTER.DLINKDIR100.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (98,'Linksys SD208 8-ports 10/100 Switch',17,51,'SWITCH.LINKSYSSD208.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (99,'Linksys SD02008 8-ports 10/100/1000 Gigabit Switch (Port3 Defekt)',17,51,'SWITCH.LINKSYSSD2008.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (100,'Linksys SD0216 16-ports 10/100 Desktop Switch',17,51,'SWITCH.LINKSYSSD216.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (101,'Netgear Fast Ethernet Switch Model FS116 Auto 10/100 Mbs',17,51,'SWITCH.NETGEARFS116.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (102,'Netgear Fast Ethernet Switch FS105 Auto 10/100 Mbps',17,51,'SWITCH.NETGEARFS105.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (103,'GreyCom GC-1408 8-port 10/100M Ethernet Mini Switch',17,51,'SWITCH.GREYCOMGC1408.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (104,'Sitecom 5-port ethernet switch 10/100 Mbps LN-112 V2',17,51,'SWITCH.SITECOMLN112V2.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (105,'8-port Fast Ethernet Switch 10/100 DES-1008D',17,51,'SWITCH.DLINKDES1008D.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (106,'Cisco PIX 501 Firewall',17,54,'FIREWALL.CISCOPIX501.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (107,'DELLPRECISIONT3500',1,98,'PC.DELLPRECISIONT3500.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (108,'Cisco 8-port 10/100/1000 Switch SD2008 V3',17,51,'SWITCH.CISCOSD2008.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (109,'GroovePi+ Starter Kit for Raspberry Pi',17,71,'PI.GROOVEKIT.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (110,'Ventilator',17,1,'VENTILATOR.BILTEMA.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (111,'Signature pad Wacom STU 540',17,1,'SIGNPAD.WACOMSTU540.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (112,'Arduino kit med Uno R3 board.',17,72,'ARDUIONOKIT.UNOR3.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (113,'Arduino kit UNOR1',17,72,'ARDUIONOKIT.UNOR1.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (114,'Inventor Kit Micro:Bit            ',17,71,'INVENTORKIT.MICROBIT.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (115,'Raspberry Pi Kit For Dummies',17,71,'PI.KITFORDUMMIES.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (116,'Electronik breadboard            ',17,71,'PI.BREADBOARD.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (117,'UniFI SWX-UAP Access Point',17,53,'AP.UNIFISWXUAP.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (118,'Synology DS215j DiskStation NAS 2x 1TB HDD',17,56,'NAS.SYNOLOGYDS215J.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (119,'MASKINE',10,98,'TEST.MASKINE.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (120,'blade',17,79,'SERVER.BLADE.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (121,'Raspberry Pi 4 desktop kit',17,71,'PI.DESKTOPKIT.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (122,'BenQ DL2215',6,97,'SKAERM.BENQDL2215.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (123,'HP M209dwe LaserJet printer (Hovedforløb)',17,64,'PRINTER.HPM209dwe.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (124,'DELL 1908FPc Skærm',1,97,'SKAERM.DELL1908FPc.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (125,'samsung galaxy tab s7+ tablet til hovedforløbs undervisere            ',4,100,'Tablet.galaxytabs7+.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (126,'Linksys EA2700 Hjemmerouter',17,50,'ROUTER.LINKSYSEA2700.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (127,'Cisco 3560 8 ports POE switch',17,51,'SWITCH.CISCO3550P8POE.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (128,'HP EliteDisplay E232',2,97,'HP E232SKAERM.HPE232.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (129,'Dell 2208WFPT skærm\r\n',1,97,'SKAERM.DELL2208WFPT.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (130,'SpeedDemon',9,98,'PC.SpeedDemon.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (131,'BordventilatorNEDIS',17,1,'VENTILATOR.NEDIS.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (132,'BordventilatorPROKLIMA',17,1,'VENTILATOR.PROKLIMA.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (133,'D-Link DGS-108\r\n8 Port Gigabit switch',17,51,'SWITCH.DLINKDGS108.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (134,'\r\nLinkSys SE2800 8-Port Switch\r\n',17,51,'SWITCH.LINKSYSSE2800P8.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (135,'Arduino starter kit',17,72,'ARDUINOKIT.STARTER.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (136,'Raspberry Pi starterkit med pi 3',17,71,'PI.STARTERKIT.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (137,'Cisco 3560 24 ports switch',17,51,'SWITCH.CISCO3560P24.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (138,'Cisco 4300 Router',17,50,'ROUTER.CISCO4300.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (139,'Cisco 2951 router',17,50,'ROUTER.CISCO2951.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (140,'Cisco 2960 24-ports switch med POE',17,51,'SWITCH.CISCO2960P24POE.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (141,'Wireless Controller Cisco 2500 ',17,53,'WLC.CISCO2500WLC.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (142,'Cisco 3560 24 ports switch med POE',17,51,'SWITCH.CISCO3560P24POE.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (143,'Cisco 5500 Wireless Controller. ',17,53,'WLC.CISCO5500WLC.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (144,'CISCO 3750 SWITCH 48-ports PoE\r\n',17,51,'SWITCH.CISCO3750P48.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (145,'CISCO ASA 5520 FIREWALL            ',17,54,'FIREWALL.CISCOASA5520.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (146,'SONICWALL 4500 FIREWALL',17,54,'FIREWALL.SW4500.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (147,'SONICWALL SSL-VPN 4000 FIREWALL',17,54,'FIREWALL.SW4000.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (148,'CISCO 4400 WIRELESS LAN CONTROLLER',17,53,'WLC.CISCO4400.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (149,'CISCO ASA 5510 FIREWALL',17,54,'FIREWALL.CISCOASA5510.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (150,'CISCO 2950 SWITCH 24-Ports',17,51,'SWITCH.CISCO2950P24.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (151,'HP 2524 SWITCH 24-Ports',17,51,'SWITCH.HP2524P24.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (152,'HP 2610 SWITCH 24-Ports PoE',17,51,'SWITCH.HP2610P24POE.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (153,'CISCO WLC 5508',17,53,'WLC.CISCO5508.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (154,'CISCO ASA 5525-X FIREWALL',17,54,'FIREWALL.CISCOASA5525.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (155,'CISCO 2901 ROUTER',17,50,'ROUTER.CISCO2901.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (156,'CISCO 4331 ROUTER',17,50,'ROUTER.CISCO4331.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (157,'AOC TFT22W90PS skærm',3,97,'SKAERM.AOCTFT22W90PS.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (158,'Linksys LGS308 8-ports gigabit smart-switch',17,51,'SWITCH.LINKSYSLGS308.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (159,'LG FLATRON W2256PM',5,97,'SKAERM.LGFLTRW2246pm.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (160,'DELL 2408WFPb SKÆRM',1,97,'SKAERM.DELL2408WFPb.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (161,'BengQ GL2250 skærm',6,97,'SKAERM.BENQGL2250.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (162,'Philips Brilliance 240S',8,97,'SKAERM.PHILIPSB240S.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (163,'Dell U2312hmt skærm',1,97,'SKAERM.DELLU2312HMt.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (164,'Dell U2410 skærm',1,97,'SKAERM.DELLU2410.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (165,'HP E23 Generation 4',2,97,'SKAERM.HPE23G40.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (166,'Dell E2414HT Skærm',1,97,'SKAERM.DELLE2414HT.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (167,'Dell U2412MC',1,97,'SKAERM.DELLu2412MC.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (168,'CISCO 3650 SWITCH 24-Ports',17,51,'SWITCH.CISCO3650P24.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (169,'Nordic Home bordventilator            ',17,1,'VENTILATOR.NORDICHOME.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (170,'HPELITEDESK800G6',2,98,'PC.HPELITEDESK800G6.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (171,'Cisco 1841 router.            ',17,50,'ROUTER.CISCO1841.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (172,'HPELITEDESK800G4',2,98,'PC.HPELITEDESK800G4.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (173,'Skruetræk-sæt',17,80,'VAERKTOEJ.SKRUETRAEK.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (174,'Raspberry Pi mus',17,81,'MUS.RPI.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (175,'LinkSys N600 Dual Band WiFi Router ',17,50,'ROUTER.LINKSYSN600.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (176,'CHIEFTEC',10,98,'PC.CHIEFTEC.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (177,'HP skærm',2,97,'SKAERM.HPE232.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (178,'HP Thunderbolt Dock G2 Combo Cable',17,45,'KABEL.HPG2TBCMBOCABLE.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (179,'HPELITEDESK800G3SFF',2,98,'PC.HPELITEDESK800G3SFF.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (180,'Oculus Quest 2 VR headset.',17,77,'VRHEADSET.OCULUSQ2.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (181,'HDMI Extension Kabel',17,32,'KABEL.HDMI-EXTENSION.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (182,'USB WIFI DONGLE',17,30,'USB.WIFIDONGLE.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (183,'HDMI til VGA Adapter',17,1,'ADAPTER.HDMI-VGA.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (184,'DisplayPort til HDMI Kabel',17,46,'KABEL.DP-HDMI.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (185,'DisplayPort til DVI Adapter',17,1,'ADAPTER.DP-DVI.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (186,'DisplayPort til HDMI Adapter',17,1,'ADAPTER.DP-HDMI.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (187,'DisplayPort til DVI Kabel',17,83,'KABEL.DP-DVI.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (188,'DisplayPort til Mini-DisplayPort',17,37,'KABEL.DP-MINIDP.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (189,'HDMI til DVI Kabel',17,47,'KABEL.HDMI-DVI.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (190,'PS/2 til USB Adapter            ',17,1,'ADAPTER.PS2-USB.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (191,'USB til Micro USB-B            ',17,87,'KABEL.USB-MICROUSB.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (192,'HDMI til Micro HDMI Kabel',17,32,'KABEL.HDMI-MICROHDMI.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (193,'Konsol til Konsol Kabel            ',17,84,'KABEL.KONSOL-KONSOL.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (194,'Cisco 1921 Router',17,50,'ROUTER.CISCO1921.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (195,'Serial til USB Adapter',17,1,'ADAPTER.SERIAL-USB.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (196,'EDB Stikdåse',17,7,'KABEL.EDB-STIKDAASE.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (197,'Forlængerledning',17,9,'KABEL.EXTENSIONCORD.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (198,'OPTPLX755',1,98,'PC.OPTPLX755.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (199,'Serial Extension Kabel',17,84,'KABEL.SERIAL-EXTENSION.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (200,'Acer B203H skærm',7,97,'SKAERM.ACERB203H.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (201,'HP E233 Skærm',2,97,'SKAERM.HPE233.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (202,'HPELITEDESK800G5',2,98,'PC.HPELITEDESK800G5.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (203,'OPTPLX7010',1,98,'PC.OPTPLX7010.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (204,'OPTPLX9020',1,98,'PC.OPTPLX9020.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (205,'MINECRAFT SERVER',17,1,'SERVER.MINECRAFT.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (206,'Cisco SG300 28-Ports Switch',17,51,'SWITCH.CISCOSG300P28.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (207,'Cisco 2960 24-Ports Switch',17,51,'SWITCH.CISCO2960P24.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (208,'D-Link Switch',17,51,'SWITCH.D+Link1016D.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (209,'Cisco 2960-C 12-ports switch med PoE',17,51,'SWITCH.CISCO2960P12POE.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (210,'RAIDCHIEFTEC',10,98,'PC.RAIDCHIEFTEC.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (211,'OPTPLX960',1,98,'PC.OPTPLX960.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (212,'LG FLTRW2343T',5,97,'SKAERM.LGFLTRW2343T.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (213,'skærm',3,97,'SKAERM.AOC24P2Q.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (214,'Synology DS416play DiskStation NAS 4x 1TB HDD',17,56,'NAS.SYNOLOGYDS416PLAY.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (215,'CISCO 3750 SWITCH 24-Ports',17,51,'SWITCH.CISCO3750P24.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (216,'Cisco 3560 48-ports switch med POE',17,51,'SWITCH.CISCO3560P48POE.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (217,'Cisco 2960X 24-ports switch',17,51,'SWITCH.CISCO2960XP24.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (218,'Cisco 2960X 48-ports switch',17,51,'SWITCH.CISCO2960XP48.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (219,'CISCO 3750G SWITCH 48-ports PoE ',17,51,'SWITCH.CISCO3750GP48.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (220,'CISCO 3750-X SWITCH 24-Ports',17,51,'SWITCH.CISCO3750XP24.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (221,'CISCO 3750-X SWITCH 48-Ports',17,51,'SWITCH.CISCO3750XP48.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (222,'Cisco 2940 8-ports switch',17,51,'SWITCH.CISCO2940P8.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (223,'IFIXIT.KIT',17,80,'IFIXIT.KIT.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (224,'Cisco ASA5505 FIREWALL',17,54,'FIREWALL.CISCOASA5505.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (225,'Cisco 3560 8-ports POE Switch',17,51,'SWITCH.CISCO3560P8POE.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (226,'fodskammel',17,89,'FOD.SKAMMEL.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (227,'DISPLAY TIL HDMI',17,46,'KABEL.DP+HDMI.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (228,'Cisco 3560G 48 ports switch',17,51,'SWITCH.CISCO3560GP48.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (229,'Cisco 3560G 24 ports switch',17,51,'SWITCH.CISCO3560GP24.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (230,'Dell Mus',17,81,'MUS.DELL.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (231,'HDMI TIL VGA',17,91,'ADAPTER.HDMI+VGA.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (232,'AUX til AUX',17,92,'KABEL.AUX.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (233,'PFSENSE',17,66,'USB.ISO.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (234,'DISPLAY',17,36,'KABEL.DP.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (235,'MINI-DISPLAY - DISPLAY',17,37,'KABEL.DP+MINIDP.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (236,'FIREWIRE800',17,93,'KABEL.FW800.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (237,'HDMI',17,32,'KABEL.HDMI.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (238,'HDMI - DVI',17,47,'KABEL.HDMI+DVI.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (239,'4x Intel Xeon X7550, 36x 8GB DDR3 RAM, 2x 600GB HDD, 300 GB HDD',17,78,'SERVER.RACKFORMAT.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (240,'USB HUN A TIL USB B',17,94,'USB.HA-V.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (241,'AC1200',17,50,'ROUTER.AC1200.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (242,'WEBCAM',17,31,'CAM.REOLINK.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (243,'KONSOL',17,84,'KABEL.KONSOL.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (244,'PROGRAMOER USB',17,30,'USB.PROGRAMOER.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (245,'AUX adapter',17,1,'AUX.ADAPTER.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (246,'USB-C-MULTIPORT',17,1,'USB-C.MULTIPORT.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (247,'My Cloud Pro',17,56,'SERVER.MYC.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (248,'STIKDÅSE',17,7,'KABEL.STIKDAASE.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (249,'LOGITECH-MUS',17,81,'MUS.LOGITECH.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (250,'VGA',17,33,'KABEL.VGA.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (251,'DVI',17,34,'KABEL.DVI.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (252,'KEYBOARD',17,82,'KEYBOARD.KB.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (253,'HP Mus',17,81,'MUS.HP.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (254,'USB-A TIL USB-B',17,88,'KABEL.USBB-USBA.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (255,'STRØMKABEL',17,39,'KABEL.POWER.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (256,'CAT 6 Modulær kabel kobler',17,1,'KOBLER.CAT6.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (257,'CISCO 3560-X SWITCH 48-Ports',17,51,'SWITCH.CISCO3560XP48.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (258,'WD Green SSD 1TB (fejl)',14,101,'SSD.HFserver1TB.0001.WD Green SSD 1TB.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (259,'WD Green SSD 1TB',14,101,'SSD.HFserver1TB.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (260,'MXVERTICAL',15,28,'MUS.MXVERTICAL.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (261,'HL-L5100DN',16,64,'Printer.L5100DN.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (262,'DellEMC',1,101,'SSD.DellEMC.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (263,'HP E23 G4',2,97,'skærm.E23G4.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (265,'Dell lattitude',1,4,'Baerbar.Lattitude.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (266,'KVM',18,102,'Kabel.KVM.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (267,'USB-Eth',1,38,'USB.Ethernet.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (268,'Switch 8',17,51,'UnifiPoE+.Switch8.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (271,'Unifi Router',17,50,'Router.Unifi8.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (272,'Custom VR PC',17,98,'VR.STATIONAERPC.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (273,'Amazon Alexa echo',19,25,'SPEAKER.ECHO.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (274,'Google Home',20,25,'SPEAKER.GOOGLEHOME.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (275,'DELL skaerm 280WFPb',1,97,'skaerm.280WFPb.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (276,'USB-C Hub',21,103,'hub.minidock.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (277,'Unifi Cloud Key',17,52,'Unifi.CloudKey.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (278,'the tinkerkit',22,104,'robotarm.tinkerkit.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (279,'Unifi AP AC lite',23,53,'network.unifiAPAClite.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (280,'Unifi Switch 8',23,51,'network.unifiSwitch8.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (281,'CISCO.SG300-28',24,51,'Network.SG300-28.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (283,'hmdi til dvi adapter',17,1,'ADAPTER.HMDI-DVI.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (284,'HDMI til USB-C',17,32,'KABEL.HDMI-USB-C.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (285,'Samsung EVO 870',4,101,'SAMSUNG.EVO870.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (286,'sandberg usb floppy drive',17,17,'usb.floppy disk.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (289,'HF Reserve',2,98,'HFReserve.G6.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (290,'Ekstra hænder',17,80,'Værktøj.EkstraHænder.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (291,'JabraHeadset',25,105,'Headset.JabraHeadset.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (292,'Dell Dockingstation',1,99,'DELL.Dockingstation.0001.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (293,'firewall pc',10,54,'firewall pc.chieftec.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (294,'Pegepind',15,2,'Pegepind.R400.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (296,'Flukeudstyr',26,106,'Fluke.Udstyr.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (297,'system x',17,101,'SSD.System x.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (298,'Kortlæser',17,107,'Kingston.Kortlaeser.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (299,'Dir-100',27,50,'Dlink.switch.Dir-100.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (300,'FS108',28,51,'Switch.NetgearFS108.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (301,'Security Gateway',23,54,'Unifi.SecurityGateway.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (302,'HDD dock',17,99,'DOCK.LCDOCK.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (311,'Samsung Galaxy A8 Tablet',4,109,'TABLET.SAM-A8.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (312,'CISCO SD2005 VER.3',24,51,'SWITCH.CISCORSD2005V.3.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (313,'Dell Precision M3800',1,4,'LAPTOP.PRE-M3800.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (314,'Raspberry PI Keyboard',29,82,'KEYBOARD.PI.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (315,'Power Supply USB',29,110,'PSU.PI.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (316,'Raspberry Pi-3 model B',29,71,'RASPBERRY.PI.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (317,'Raspberry Pi-3 Black',30,71,'PI.BLACKKIT.');
INSERT INTO `products` (`UUID`,`name`,`brand_id`,`category_id`,`product_id_prefix`) VALUES (320,'CoolermasterFirewall',31,98,'Stationaer.Firewall.');
